"""
Build the public GitHub Pages site.

Only HTML report pages are copied into site/. Data files, workbooks, source
code, and CSV exports are intentionally excluded from the published artifact.
"""
from __future__ import annotations

import glob
import html
import os
import re
import shutil
from dataclasses import dataclass
from datetime import datetime


BASE = os.path.dirname(os.path.abspath(__file__))
SITE_DIR = os.path.join(BASE, "site")
DATE_RE = re.compile(r"_(\d{8})(?:_(AM|PM))?\.html$")


@dataclass(frozen=True)
class Page:
    filename: str
    date_key: str
    slot: str

    @property
    def label(self) -> str:
        try:
            dt = datetime.strptime(self.date_key, "%Y%m%d")
            date_text = dt.strftime("%b %-d, %Y")
        except ValueError:
            date_text = self.date_key
        return f"CEO Brief - {date_text} {self.slot}".strip()


def collect_pages() -> list[Page]:
    pages: list[Page] = []
    for path in glob.glob(os.path.join(BASE, "CEO_Brief_*.html")):
        filename = os.path.basename(path)
        match = DATE_RE.search(filename)
        date_key = match.group(1) if match else "00000000"
        slot = match.group(2) or ""
        pages.append(Page(filename=filename, date_key=date_key, slot=slot))
    return sorted(pages, key=lambda page: (page.date_key, page.slot, page.filename), reverse=True)


def copy_html_pages(pages: list[Page]) -> None:
    if os.path.exists(SITE_DIR):
        shutil.rmtree(SITE_DIR)
    os.makedirs(SITE_DIR, exist_ok=True)

    for page in pages:
        shutil.copy2(os.path.join(BASE, page.filename), os.path.join(SITE_DIR, page.filename))

    with open(os.path.join(SITE_DIR, ".nojekyll"), "w", encoding="utf-8") as f:
        f.write("")


def build_index(pages: list[Page]) -> None:
    latest = pages[0].filename if pages else ""
    latest_button = (
        f'<a class="primary" href="{html.escape(latest)}">Open latest CEO brief</a>'
        if latest
        else '<span class="primary disabled">No CEO brief has been generated yet</span>'
    )
    links = "\n".join(
        f'<a class="report-link" href="{html.escape(page.filename)}">{html.escape(page.label)}</a>'
        for page in pages
    ) or '<p class="empty">No CEO brief pages found.</p>'

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SYTE BD Pipeline</title>
  <style>
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f6f8fb;
      color: #18243d;
      line-height: 1.5;
    }}
    header {{
      background: #17233d;
      color: white;
      padding: 28px 22px;
    }}
    .wrap {{
      width: min(860px, calc(100% - 32px));
      margin: 0 auto;
    }}
    .eyebrow {{
      color: #91c4ff;
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 1.2px;
      text-transform: uppercase;
    }}
    h1 {{
      margin: 6px 0 8px;
      font-size: clamp(28px, 5vw, 42px);
      line-height: 1.1;
    }}
    .summary {{
      max-width: 660px;
      color: #d9e4f2;
      margin: 0 0 20px;
    }}
    .primary {{
      display: inline-flex;
      align-items: center;
      min-height: 44px;
      padding: 0 16px;
      border-radius: 8px;
      background: #2e86ab;
      color: white;
      text-decoration: none;
      font-weight: 700;
    }}
    .primary.disabled {{
      background: #64748b;
    }}
    main {{
      padding: 24px 0 42px;
    }}
    h2 {{
      font-size: 16px;
      margin: 0 0 10px;
      color: #e94f37;
      text-transform: uppercase;
      letter-spacing: 0.8px;
    }}
    .report-list {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 10px;
    }}
    .report-link {{
      display: flex;
      align-items: center;
      min-height: 56px;
      padding: 13px 14px;
      border: 1px solid #dbe3ef;
      border-radius: 8px;
      background: white;
      color: #17233d;
      text-decoration: none;
      font-weight: 650;
    }}
    .report-link:hover {{
      border-color: #2e86ab;
    }}
    .empty, footer {{
      color: #64748b;
      font-size: 13px;
    }}
    footer {{
      margin-top: 28px;
    }}
  </style>
</head>
<body>
  <header>
    <div class="wrap">
      <div class="eyebrow">SYTE Corp</div>
      <h1>BD Pipeline Reports</h1>
      <p class="summary">Web-only CEO decision briefs generated by the automated SAM.gov business development pipeline.</p>
      {latest_button}
    </div>
  </header>
  <main class="wrap">
    <h2>CEO Briefs</h2>
    <div class="report-list">
      {links}
    </div>
    <footer>Generated {html.escape(generated_at)}. Excel and CSV files are not published on this site.</footer>
  </main>
</body>
</html>
"""
    with open(os.path.join(SITE_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(content)


def main() -> None:
    pages = collect_pages()
    copy_html_pages(pages)
    build_index(pages)


if __name__ == "__main__":
    main()
